/////// AUTOMATICALLY GENERATED BY T4 GENERATOR PitManagerEventHandlersTable_RF2.tt
/////// but commit to git anyway as Build doesn't run the T4 transform automatically 

using static CrewChiefV4.PitManager.PitManager;

namespace CrewChiefV4.PitManager
{
    using PME = PitManagerEvent;  // shorthand
    using PMER = PitManagerResponseHandlers;
    using SRE = SpeechRecogniser;
    public partial class PitManagerEventHandlers_RF2
    {
        /// <summary>
        /// The event dictionary for rF2
        /// </summary>
        internal static readonly GamePitManagerDict PM_event_dict_RF2 = new GamePitManagerDict
        {
            // The event                                      the fn that implements it          the fn that handles speech response     Speech strings for command
            //                                                (changes the pit menu)             and any other outcomes                  
            {PME.Initialise,                   _PMet(_PMeh,   EH_initialise,                     PMER.PMrh_NoResponse,                   null)},
            {PME.Teardown,                     _PMet(_PMeh,   EH_teardown,                       PMER.PMrh_NoResponse,                   null)},
            {PME.PrepareToUseMenu,             _PMet(_PMeh,   EH_prepareToUseMenu,               PMER.PMrh_NoResponse,                   null)},

            // Fuel                                                                                                                      
            {PME.FuelAddXlitres,               _PMet(_PMeh,   EH_FuelAddXlitres,                 PMER.PMrh_FuelAddXlitres,               SRE.PIT_STOP_ADD)},
            {PME.FuelFillToXlitres,            _PMet(_PMeh,   EH_FuelToXlitres,                  PMER.PMrh_FuelAddXlitres,               SRE.PIT_STOP_FILL_TO)},
            {PME.FuelNone,                     _PMet(_PMeh,   EH_FuelNone,                       PMER.PMrh_noFuel,                       SRE.PIT_STOP_DONT_REFUEL)},
            {PME.FuelFillToEnd,                _PMet(_PMeh,   EH_FuelToEnd,                      PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FUEL_TO_THE_END)},

            // Tyres                                                                                                                     
            {PME.TyreChangeAll,                _PMet(_PMeh,   EH_changeAllTyres,                 PMER.PMrh_ChangeAllTyres,               SRE.PIT_STOP_CHANGE_ALL_TYRES)},
            {PME.TyreChangeNone,               _PMet(_PMeh,   EH_changeNoTyres,                  PMER.PMrh_ChangeNoTyres,                SRE.PIT_STOP_CLEAR_TYRES)},
            {PME.TyreChangeFront,              _PMet(_PMeh,   EH_changeFrontTyres,               PMER.PMrh_ChangeFrontTyres,             SRE.PIT_STOP_CHANGE_FRONT_TYRES)},
            {PME.TyreChangeRear,               _PMet(_PMeh,   EH_changeRearTyres,                PMER.PMrh_ChangeRearTyres,              SRE.PIT_STOP_CHANGE_REAR_TYRES)},
            {PME.TyreChangeLeft,               _PMet(_PMeh,   EH_changeLeftTyres,                PMER.PMrh_ChangeLeftTyres,              SRE.PIT_STOP_CHANGE_LEFT_SIDE_TYRES)},
            {PME.TyreChangeRight,              _PMet(_PMeh,   EH_changeRightTyres,               PMER.PMrh_ChangeRightTyres,             SRE.PIT_STOP_CHANGE_RIGHT_SIDE_TYRES)},
            {PME.TyreChangeLF,                 _PMet(_PMeh,   EH_changeFLTyre,                   PMER.PMrh_ChangeFrontLeftTyre,          SRE.PIT_STOP_CHANGE_FRONT_LEFT_TYRE)},
            {PME.TyreChangeRF,                 _PMet(_PMeh,   EH_changeFRTyre,                   PMER.PMrh_ChangeFrontRightTyre,         SRE.PIT_STOP_CHANGE_FRONT_RIGHT_TYRE)},
            {PME.TyreChangeLR,                 _PMet(_PMeh,   EH_changeRLTyre,                   PMER.PMrh_ChangeRearLeftTyre,           SRE.PIT_STOP_CHANGE_REAR_LEFT_TYRE)},
            {PME.TyreChangeRR,                 _PMet(_PMeh,   EH_changeRRTyre,                   PMER.PMrh_ChangeRearRightTyre,          SRE.PIT_STOP_CHANGE_REAR_RIGHT_TYRE)},

            {PME.TyreCompoundHard,             _PMet(_PMeh,   EH_TyreCompoundHard,               PMER.PMrh_TyreCompoundHard,             SRE.PIT_STOP_HARD_TYRES)},
            {PME.TyreCompoundMedium,           _PMet(_PMeh,   EH_TyreCompoundMedium,             PMER.PMrh_TyreCompoundMedium,           SRE.PIT_STOP_MEDIUM_TYRES)},
            {PME.TyreCompoundSoft,             _PMet(_PMeh,   EH_TyreCompoundSoft,               PMER.PMrh_TyreCompoundSoft,             SRE.PIT_STOP_SOFT_TYRES)},
            {PME.TyreCompoundSupersoft,        _PMet(_PMeh,   EH_TyreCompoundSupersoft,          PMER.PMrh_TyreCompoundSupersoft,        SRE.PIT_STOP_SUPERSOFT_TYRES)},
            {PME.TyreCompoundUltrasoft,        _PMet(_PMeh,   EH_TyreCompoundUltrasoft,          PMER.PMrh_TyreCompoundUltrasoft,        SRE.PIT_STOP_ULTRASOFT_TYRES)},
            {PME.TyreCompoundHypersoft,        _PMet(_PMeh,   EH_TyreCompoundHypersoft,          PMER.PMrh_TyreCompoundHypersoft,        SRE.PIT_STOP_HYPERSOFT_TYRES)},
            {PME.TyreCompoundPrime,            _PMet(_PMeh,   EH_TyreCompoundPrime,              PMER.PMrh_TyreCompoundPrime,            SRE.PIT_STOP_PRIME_TYRES)},
            {PME.TyreCompoundOption,           _PMet(_PMeh,   EH_TyreCompoundOption,             PMER.PMrh_TyreCompoundOption,           SRE.PIT_STOP_OPTION_TYRES)},
            {PME.TyreCompoundAlternate,        _PMet(_PMeh,   EH_TyreCompoundAlternate,          PMER.PMrh_TyreCompoundAlternate,        SRE.PIT_STOP_ALTERNATE_TYRES)},
            {PME.TyreCompoundIntermediate,     _PMet(_PMeh,   EH_TyreCompoundIntermediate,       PMER.PMrh_TyreCompoundIntermediate,     SRE.PIT_STOP_INTERMEDIATE_TYRES)},
            {PME.TyreCompoundWet,              _PMet(_PMeh,   EH_TyreCompoundWet,                PMER.PMrh_TyreCompoundWet,              SRE.PIT_STOP_WET_TYRES)},
            {PME.TyreCompoundMonsoon,          _PMet(_PMeh,   EH_TyreCompoundMonsoon,            PMER.PMrh_TyreCompoundMonsoon,          SRE.PIT_STOP_MONSOON_TYRES)},
            {PME.TyreCompoundNext,             _PMet(_PMeh,   EH_TyreCompoundNext,               PMER.PMrh_TyreCompoundNext,             SRE.PIT_STOP_NEXT_TYRE_COMPOUND)},

            {PME.TyrePressureFront,            _PMet(_PMeh,   EH_changeFrontPressure,            PMER.PMrh_Acknowledge,                  SRE.PIT_STOP_CHANGE_FRONT_PRESSURES)},
            {PME.TyrePressureRear,             _PMet(_PMeh,   EH_changeRearPressure,             PMER.PMrh_Acknowledge,                  SRE.PIT_STOP_CHANGE_REAR_PRESSURES)},
            {PME.TyrePressureLF,               _PMet(_PMeh,   EH_changeLFpressure,               PMER.PMrh_Acknowledge,                  SRE.PIT_STOP_CHANGE_FRONT_LEFT_TYRE_PRESSURE)},
            {PME.TyrePressureRF,               _PMet(_PMeh,   EH_changeRFpressure,               PMER.PMrh_Acknowledge,                  SRE.PIT_STOP_CHANGE_FRONT_RIGHT_TYRE_PRESSURE)},
            {PME.TyrePressureLR,               _PMet(_PMeh,   EH_changeLRpressure,               PMER.PMrh_Acknowledge,                  SRE.PIT_STOP_CHANGE_REAR_LEFT_TYRE_PRESSURE)},
            {PME.TyrePressureRR,               _PMet(_PMeh,   EH_changeRRpressure,               PMER.PMrh_Acknowledge,                  SRE.PIT_STOP_CHANGE_REAR_RIGHT_TYRE_PRESSURE)},

            // Repairs                                                                                                                   
            {PME.RepairBody,                   _PMet(_PMeh,   EH_RepairBody,                     PMER.PMrh_RepairBody,                   SRE.PIT_STOP_FIX_BODY)},
            {PME.RepairAll,                    _PMet(_PMeh,   EH_RepairAll,                      PMER.PMrh_RepairAll,                    SRE.PIT_STOP_FIX_ALL)},
            {PME.RepairNone,                   _PMet(_PMeh,   EH_RepairNone,                     PMER.PMrh_RepairNone,                   SRE.PIT_STOP_FIX_NONE)},

            // Penalties                                                                                                                 
            {PME.PenaltyServe,                 _PMet(_PMeh,   EH_PenaltyServe,                   PMER.PMrh_ServePenalty,                 SRE.PIT_STOP_SERVE_PENALTY)},
            {PME.PenaltyServeNone,             _PMet(_PMeh,   EH_PenaltyServeNone,               PMER.PMrh_DontServePenalty,             SRE.PIT_STOP_DONT_SERVE_PENALTY)},

            // Misc                                                                                                                      
            {PME.ClearAll,                     _PMet(_PMeh,   EH_ClearAll,                       PMER.PMrh_Acknowledge,                  SRE.PIT_STOP_CLEAR_ALL)},

            // rF2 MFD                                                                                                                   
            {PME.DisplaySectors,               _PMet(_PMeh,   EH_DisplaySectors,                 PMER.PMrh_NoResponse,                   SRE.DISPLAY_SECTORS)},
            {PME.DisplayPitMenu,               _PMet(_PMeh,   EH_DisplayPitMenu,                 PMER.PMrh_NoResponse,                   SRE.DISPLAY_PIT_MENU)},
            {PME.DisplayTyres,                 _PMet(_PMeh,   EH_DisplayTyres,                   PMER.PMrh_NoResponse,                   SRE.DISPLAY_TYRES)},
            {PME.DisplayTemps,                 _PMet(_PMeh,   EH_DisplayTemps,                   PMER.PMrh_NoResponse,                   SRE.DISPLAY_TEMPS)},
            {PME.DisplayRaceInfo,              _PMet(_PMeh,   EH_DisplayRaceInfo,                PMER.PMrh_NoResponse,                   SRE.DISPLAY_RACE_INFO)},
            {PME.DisplayStandings,             _PMet(_PMeh,   EH_DisplayStandings,               PMER.PMrh_NoResponse,                   SRE.DISPLAY_STANDINGS)},
            {PME.DisplayPenalties,             _PMet(_PMeh,   EH_DisplayPenalties,               PMER.PMrh_NoResponse,                   SRE.DISPLAY_PENALTIES)},
            {PME.DisplayNext,                  _PMet(_PMeh,   EH_DisplayNext,                    PMER.PMrh_NoResponse,                   SRE.DISPLAY_NEXT)},
        };
    }
}

