/////// AUTOMATICALLY GENERATED BY T4 GENERATOR PitManagerEventHandlersTable_R3E.tt
/////// but commit to git anyway as Build doesn't run the T4 transform automatically 

using static CrewChiefV4.PitManager.PitManager;

namespace CrewChiefV4.PitManager
{
    using PME = PitManagerEvent;  // shorthand
    using PMER = PitManagerResponseHandlers;
    using SRE = SpeechRecogniser;
    public partial class PitManagerEventHandlers_R3E
    {
        /// <summary>
        /// The event dictionary for R3E
        /// </summary>
        internal static readonly GamePitManagerDict PM_event_dict_R3E = new GamePitManagerDict
        {
            // The event                                      the fn that implements it          the fn that handles speech response     Speech strings for command
            //                                                (changes the pit menu)             and any other outcomes                  
            {PME.Initialise,                   _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   null)},
            {PME.Teardown,                     _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   null)},
            {PME.PrepareToUseMenu,             _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   null)},

            // Fuel                                                                                                                      
            {PME.FuelNone,                     _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_DONT_REFUEL)},
            {PME.Refuel,                       _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_REFUEL)},

            // Tyres                                                                                                                     
            {PME.TyreChangeAll,                _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_ALL_TYRES)},
            {PME.TyreChangeNone,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CLEAR_TYRES)},
            {PME.TyreChangeFront,              _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_FRONT_TYRES)},
            {PME.TyreChangeRear,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_REAR_TYRES)},

            {PME.TyreCompoundHard,             _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_HARD_TYRES)},
            {PME.TyreCompoundMedium,           _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_MEDIUM_TYRES)},
            {PME.TyreCompoundSoft,             _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_SOFT_TYRES)},
            {PME.TyreCompoundSupersoft,        _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_SUPERSOFT_TYRES)},
            {PME.TyreCompoundPrime,            _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_PRIME_TYRES)},
            {PME.TyreCompoundOption,           _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_OPTION_TYRES)},
            {PME.TyreCompoundAlternate,        _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_ALTERNATE_TYRES)},
            {PME.TyreCompoundIntermediate,     _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_INTERMEDIATE_TYRES)},
            {PME.TyreCompoundWet,              _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_WET_TYRES)},
            {PME.TyreCompoundNext,             _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_NEXT_TYRE_COMPOUND)},


            // Repairs                                                                                                                   
            {PME.RepairAllAero,                _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FIX_ALL_AERO)},
            {PME.RepairAeroNone,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FIX_NO_AERO)},
            {PME.RepairFrontAero,              _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FIX_FRONT_AERO)},
            {PME.RepairRearAero,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FIX_REAR_AERO)},
            {PME.RepairSuspension,             _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FIX_SUSPENSION)},
            {PME.RepairSuspensionNone,         _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_DONT_FIX_SUSPENSION)},
            {PME.RepairBody,                   _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FIX_BODY)},
            {PME.RepairAll,                    _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FIX_ALL)},
            {PME.RepairNone,                   _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FIX_NONE)},

            // Penalties                                                                                                                 
            {PME.PenaltyServe,                 _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_SERVE_PENALTY)},
            {PME.PenaltyServeNone,             _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_DONT_SERVE_PENALTY)},




        };
    // EH is not used by ACC, only the speech strings
    static private bool EH_null(string __)
        {
            return false;
        }
    }
}

