/////// AUTOMATICALLY GENERATED BY T4 GENERATOR PitManagerEventHandlersTable_iRacing.tt
/////// but commit to git anyway as Build doesn't run the T4 transform automatically 

using static CrewChiefV4.PitManager.PitManager;

namespace CrewChiefV4.PitManager
{
    using PME = PitManagerEvent;  // shorthand
    using PMER = PitManagerResponseHandlers;
    using SRE = SpeechRecogniser;
    public partial class PitManagerEventHandlers_iRacing
    {
        /// <summary>
        /// The event dictionary for iRacing
        /// </summary>
        internal static readonly GamePitManagerDict PM_event_dict_iRacing = new GamePitManagerDict
        {
            // The event                                      the fn that implements it          the fn that handles speech response     Speech strings for command
            //                                                (changes the pit menu)             and any other outcomes                  
            {PME.Initialise,                   _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   null)},
            {PME.Teardown,                     _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   null)},
            {PME.PrepareToUseMenu,             _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   null)},

            // Fuel                                                                                                                      
            {PME.FuelAddXlitres,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_ADD)},
            {PME.FuelFillToXlitres,            _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FILL_TO)},
            {PME.FuelNone,                     _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_DONT_REFUEL)},
            {PME.FuelFillToEnd,                _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FUEL_TO_THE_END)},

            // Tyres                                                                                                                     
            {PME.TyreChangeAll,                _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_ALL_TYRES)},
            {PME.TyreChangeNone,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CLEAR_TYRES)},
            {PME.TyreChangeFront,              _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_FRONT_TYRES)},
            {PME.TyreChangeRear,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_REAR_TYRES)},
            {PME.TyreChangeLeft,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_LEFT_SIDE_TYRES)},
            {PME.TyreChangeRight,              _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_RIGHT_SIDE_TYRES)},
            {PME.TyreChangeLF,                 _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_FRONT_LEFT_TYRE)},
            {PME.TyreChangeRF,                 _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_FRONT_RIGHT_TYRE)},
            {PME.TyreChangeLR,                 _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_REAR_LEFT_TYRE)},
            {PME.TyreChangeRR,                 _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_REAR_RIGHT_TYRE)},


            {PME.TyrePressure,                 _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_TYRE_PRESSURE)},
            {PME.TyrePressureLF,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_FRONT_LEFT_TYRE_PRESSURE)},
            {PME.TyrePressureRF,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_FRONT_RIGHT_TYRE_PRESSURE)},
            {PME.TyrePressureLR,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_REAR_LEFT_TYRE_PRESSURE)},
            {PME.TyrePressureRR,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_REAR_RIGHT_TYRE_PRESSURE)},

            // Repairs                                                                                                                   
            {PME.RepairFast,                   _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FAST_REPAIR)},
            {PME.RepairNone,                   _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CLEAR_FAST_REPAIR)},
            {PME.RepairAll,                    _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FIX_ALL)},

            // Misc                                                                                                                      
            {PME.TearOff,                      _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_TEAROFF)},
            {PME.TearOffNone,                  _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CLEAR_WIND_SCREEN)},
            {PME.ClearAll,                     _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CLEAR_ALL)},
            {PME.HowManyIncidentPoints,        _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.HOW_MANY_INCIDENT_POINTS)},
            {PME.WhatsTheIncidentLimit,        _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.WHATS_THE_INCIDENT_LIMIT)},
            {PME.WhatsMyIrating,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.WHATS_MY_IRATING)},
            {PME.WhatsMyLicenseClass,          _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.WHATS_MY_LICENSE_CLASS)},
            {PME.WhatsTheSof,                  _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.WHATS_THE_SOF)},

        };
    // EH is not used by ACC, only the speech strings
    static private bool EH_null(string __)
        {
            return false;
        }
    }
}

