/////// AUTOMATICALLY GENERATED BY T4 GENERATOR PitManagerEventHandlersTable_ACC.tt
/////// but commit to git anyway as Build doesn't run the T4 transform automatically 

using static CrewChiefV4.PitManager.PitManager;

namespace CrewChiefV4.PitManager
{
    using PME = PitManagerEvent;  // shorthand
    using PMER = PitManagerResponseHandlers;
    using SRE = SpeechRecogniser;
    public partial class PitManagerEventHandlers_ACC
    {
        /// <summary>
        /// The event dictionary for ACC
        /// </summary>
        internal static readonly GamePitManagerDict PM_event_dict_ACC = new GamePitManagerDict
        {
            // The event                                      the fn that implements it          the fn that handles speech response     Speech strings for command
            //                                                (changes the pit menu)             and any other outcomes                  
            {PME.Initialise,                   _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   null)},
            {PME.Teardown,                     _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   null)},
            {PME.PrepareToUseMenu,             _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   null)},

            // Fuel                                                                                                                      
            {PME.FuelAddXlitres,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_ADD)},
            {PME.FuelFillToXlitres,            _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FILL_TO)},
            {PME.FuelNone,                     _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_DONT_REFUEL)},
            {PME.FuelFillToEnd,                _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FUEL_TO_THE_END)},

            // Tyres                                                                                                                     
            {PME.TyreChangeAll,                _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_ALL_TYRES)},
            {PME.TyreChangeNone,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CLEAR_TYRES)},

            {PME.TyreCompoundDry,              _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_DRY_TYRES)},
            {PME.TyreCompoundWet,              _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_WET_TYRES)},

            {PME.TyreSet,                      _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_SELECT_TYRE_SET)},
            {PME.LeastUsedTyreSet,             _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_SELECT_LEAST_USED_TYRE_SET)},

            {PME.TyrePressure,                 _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_TYRE_PRESSURE)},
            {PME.TyrePressureFront,            _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_FRONT_PRESSURES)},
            {PME.TyrePressureRear,             _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_REAR_PRESSURES)},
            {PME.TyrePressureLF,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_FRONT_LEFT_TYRE_PRESSURE)},
            {PME.TyrePressureRF,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_FRONT_RIGHT_TYRE_PRESSURE)},
            {PME.TyrePressureLR,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_REAR_LEFT_TYRE_PRESSURE)},
            {PME.TyrePressureRR,               _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_CHANGE_REAR_RIGHT_TYRE_PRESSURE)},

            // Repairs                                                                                                                   
            {PME.RepairAll,                    _PMet(_PMeh,   EH_null,                           PMER.PMrh_NoResponse,                   SRE.PIT_STOP_FIX_ALL)},








        };
    // EH is not used by ACC, only the speech strings
    static private bool EH_null(string __)
        {
            return false;
        }
    }
}

