using System;
using System.Collections.Generic;

namespace CrewChiefV4
{
    /// <summary>
    /// Convert recognised speech or controller button label into a SpeechCommand enum
    /// </summary>
    public class SpeechCommands
    {
        #region IDs and tables
        /// <summary>
        /// Identifier for every speech command
        /// </summary>
        public enum ID
        {
            CALCULATE_FUEL_FOR,
            CAR_STATUS,
            CHART_COMMAND_ADD,
            CHART_COMMAND_BEST_LAP,
            CHART_COMMAND_OPPONENT_BEST_LAP,
            CHART_COMMAND_PAN_LEFT,
            CHART_COMMAND_PAN_RIGHT,
            CHART_COMMAND_REMOVE,
            CHART_COMMAND_RESET_ZOOM,
            CHART_COMMAND_SHOW_ALL_SECTORS,
            CHART_COMMAND_SHOW_LAST_LAP,
            CHART_COMMAND_SHOW_NEXT_LAP,
            CHART_COMMAND_SHOW_PREVIOUS_LAP,
            CHART_COMMAND_SHOW_SECTOR_1,
            CHART_COMMAND_SHOW_SECTOR_2,
            CHART_COMMAND_SHOW_SECTOR_3,
            CHART_COMMAND_ZOOM_IN,
            CHART_COMMAND_ZOOM_OUT,
            CLEAR_ALARM_CLOCK,
            CLEAR_CHART,
            CLEAR_DATA,
            DAMAGE_REPORT,
            DISABLE_CUT_TRACK_WARNINGS,
            DISABLE_MANUAL_FORMATION_LAP,
            DISABLE_YELLOW_FLAG_MESSAGES,
            DO_I_HAVE_A_MANDATORY_PIT_STOP,
            DO_I_HAVE_A_PENALTY,
            DO_I_STILL_HAVE_A_PENALTY,
            DONT_TALK_IN_THE_CORNERS,
            DONT_TELL_ME_THE_GAPS,
            ENABLE_CUT_TRACK_WARNINGS,
            ENABLE_MANUAL_FORMATION_LAP,
            ENABLE_YELLOW_FLAG_MESSAGES,
            GALLONS,
            GAME_QUIETER,
            GAME_LOUDER,
            HAVE_I_SERVED_MY_PENALTY,
            HIDE_CHART,
            HIDE_CONSOLE,
            HIDE_OVERLAY,
            HIDE_SUBTITLES,
            HIDE_VR_SETTING,
            HOURS,
            HOW_ARE_MY_BRAKE_TEMPS,
            HOW_ARE_MY_ENGINE_TEMPS,
            HOW_ARE_MY_FRONT_TYRE_PRESSURES,
            HOW_ARE_MY_FRONT_TYRE_PRESSURES_RIGHT_NOW,
            HOW_ARE_MY_REAR_TYRE_PRESSURES,
            HOW_ARE_MY_REAR_TYRE_PRESSURES_RIGHT_NOW,
            HOW_ARE_MY_TYRE_PRESSURES,
            HOW_ARE_MY_TYRE_PRESSURES_RIGHT_NOW,
            HOW_ARE_MY_TYRE_TEMPS,
            HOW_GOOD_IS,
            HOW_LONG_WILL_THESE_TYRES_LAST,
            HOW_LONGS_LEFT,
            HOW_MANY_DRS_ACTIVATIONS_LEFT,
            HOW_MANY_INCIDENT_POINTS,
            HOW_MANY_LAPS_ON_TYRE_SET,
            HOW_MANY_LAPS_SINCE_PITTING,
            HOW_MUCH_FUEL_TO_END_OF_RACE,
            HOW_OLD_ARE_THESE_TYRES,
            HOWS_MY_AERO,
            HOWS_MY_BATTERY,
            HOWS_MY_BRAKES,
            HOWS_MY_ENGINE,
            HOWS_MY_FRONT_CAMBER,
            HOWS_MY_FRONT_CAMBER_RIGHT_NOW,
            HOWS_MY_FUEL,
            HOWS_MY_LEFT_FRONT_CAMBER,
            HOWS_MY_LEFT_FRONT_CAMBER_RIGHT_NOW,
            HOWS_MY_LEFT_REAR_CAMBER,
            HOWS_MY_LEFT_REAR_CAMBER_RIGHT_NOW,
            HOWS_MY_PACE,
            HOWS_MY_REAR_CAMBER,
            HOWS_MY_REAR_CAMBER_RIGHT_NOW,
            HOWS_MY_RIGHT_FRONT_CAMBER,
            HOWS_MY_RIGHT_FRONT_CAMBER_RIGHT_NOW,
            HOWS_MY_RIGHT_REAR_CAMBER,
            HOWS_MY_RIGHT_REAR_CAMBER_RIGHT_NOW,
            HOWS_MY_SELF_PACE,
            HOWS_MY_SUSPENSION,
            HOWS_MY_TRANSMISSION,
            HOWS_MY_TYRE_WEAR,
            IS_CAR_AHEAD_MY_CLASS,
            IS_CAR_BEHIND_MY_CLASS,
            IS_MY_PIT_BOX_OCCUPIED,
            KEEP_ME_INFORMED,
            KEEP_QUIET,
            NOTE_BAD_DRIVER_AHEAD_ON_TRACK,
            NOTE_BAD_DRIVER_BEHIND_ON_TRACK,
            PIT_STOP_ADD,
            PIT_STOP_ALTERNATE_TYRES,
            PIT_STOP_CHANGE_ALL_TYRES,
            PIT_STOP_CHANGE_FRONT_LEFT_TYRE,
            PIT_STOP_CHANGE_FRONT_LEFT_TYRE_PRESSURE,
            PIT_STOP_CHANGE_FRONT_PRESSURES,
            PIT_STOP_CHANGE_FRONT_RIGHT_TYRE,
            PIT_STOP_CHANGE_FRONT_RIGHT_TYRE_PRESSURE,
            PIT_STOP_CHANGE_FRONT_TYRES,
            PIT_STOP_CHANGE_LEFT_SIDE_TYRES,
            PIT_STOP_CHANGE_REAR_LEFT_TYRE,
            PIT_STOP_CHANGE_REAR_LEFT_TYRE_PRESSURE,
            PIT_STOP_CHANGE_REAR_PRESSURES,
            PIT_STOP_CHANGE_REAR_RIGHT_TYRE,
            PIT_STOP_CHANGE_REAR_RIGHT_TYRE_PRESSURE,
            PIT_STOP_CHANGE_REAR_TYRES,
            PIT_STOP_CHANGE_RIGHT_SIDE_TYRES,
            PIT_STOP_CHANGE_TYRE_PRESSURE,
            PIT_STOP_CHANGE_TYRES,
            PIT_STOP_CLEAR_ALL,
            PIT_STOP_CLEAR_FAST_REPAIR,
            PIT_STOP_CLEAR_FUEL,
            PIT_STOP_CLEAR_TYRES,
            PIT_STOP_CLEAR_WIND_SCREEN,
            PIT_STOP_DONT_FIX_SUSPENSION,
            PIT_STOP_DONT_REFUEL,
            PIT_STOP_DONT_SERVE_PENALTY,
            PIT_STOP_DRY_TYRES,
            PIT_STOP_FAST_REPAIR,
            PIT_STOP_FIX_ALL,
            PIT_STOP_FIX_ALL_AERO,
            PIT_STOP_FIX_BODY,
            PIT_STOP_FIX_FRONT_AERO,
            PIT_STOP_FIX_NO_AERO,
            PIT_STOP_FIX_NONE,
            PIT_STOP_FIX_REAR_AERO,
            PIT_STOP_FIX_SUSPENSION,
            PIT_STOP_FUEL_TO_THE_END,
            PIT_STOP_FUEL_RATIO,
            PIT_STOP_VIRTUAL_ENERGY,
            PIT_STOP_HARD_TYRES,
            PIT_STOP_MEDIUM_TYRES,
            PIT_STOP_NEXT_TYRE_COMPOUND,
            PIT_STOP_OPTION_TYRES,
            PIT_STOP_PRIME_TYRES,
            PIT_STOP_REFUEL,
            PIT_STOP_SELECT_LEAST_USED_TYRE_SET,
            PIT_STOP_SELECT_TYRE_SET,
            PIT_STOP_SERVE_PENALTY,
            PIT_STOP_SOFT_TYRES,
            PIT_STOP_SUPERSOFT_TYRES,
            PIT_STOP_TEAROFF,
            PIT_STOP_USED_HARD_TYRES,
            PIT_STOP_USED_MEDIUM_TYRES,
            PIT_STOP_USED_SOFT_TYRES,
            PIT_STOP_WET_TYRES,
            PLAY_CORNER_NAMES,
            PLAY_POST_PIT_POSITION_ESTIMATE,
            PRACTICE_PIT_STOP,
            RADIO_CHECK,
            RALLY_1,
            RALLY_2,
            RALLY_3,
            RALLY_4,
            RALLY_5,
            RALLY_6,
            RALLY_AND,
            RALLY_BAD_CAMBER,
            RALLY_BIG_JUMP,
            RALLY_BRAKE,
            RALLY_BRIDGE,
            RALLY_BUMPS,
            RALLY_CARE,
            RALLY_CAUTION,
            RALLY_CONCRETE,
            RALLY_CORNER_DECRIPTIONS,
            RALLY_CORNER_DIRECTION_FIRST,
            RALLY_CORNER_NUMBER_FIRST,
            RALLY_CORRECTION,
            RALLY_CREST,
            RALLY_CUT,
            RALLY_DANGER,
            RALLY_DEEP_RUTS,
            RALLY_DIP,
            RALLY_DISTANCE,
            RALLY_DONT_CUT,
            RALLY_DOUBLE_CAUTION,
            RALLY_DOWNHILL,
            RALLY_EARLIER,
            RALLY_EARLIER_CALLS,
            RALLY_FINISH_RECORDING_STAGE_NOTES,
            RALLY_FLAT,
            RALLY_FORD,
            RALLY_GO_STRAIGHT,
            RALLY_GRAVEL,
            RALLY_HAIRPIN,
            RALLY_INSERT,
            RALLY_INTO,
            RALLY_JUMP,
            RALLY_JUNCTION,
            RALLY_KEEP_IN,
            RALLY_KEEP_LEFT,
            RALLY_KEEP_MIDDLE,
            RALLY_KEEP_OUT,
            RALLY_KEEP_RIGHT,
            RALLY_LATER,
            RALLY_LATER_CALLS,
            RALLY_LEFT,
            RALLY_LEFT_ENTRY_CHICANE,
            RALLY_LOGS_INSIDE,
            RALLY_LOGS_OUTSIDE,
            RALLY_LONG,
            RALLY_LONGLONG,
            RALLY_LOOSE_GRAVEL,
            RALLY_MAYBE,
            RALLY_MINUS,
            RALLY_NARROWS,
            RALLY_OPEN_HAIRPIN,
            RALLY_OPENS,
            RALLY_OPENS_THEN_TIGHTENS,
            RALLY_OVER_BRIDGE,
            RALLY_OVER_CREST,
            RALLY_OVER_JUMP,
            RALLY_OVER_RAILS,
            RALLY_PLUS,
            RALLY_RIGHT,
            RALLY_RIGHT_ENTRY_CHICANE,
            RALLY_ROCKS_INSIDE,
            RALLY_ROCKS_OUTSIDE,
            RALLY_RUTS,
            RALLY_SLIPPY,
            RALLY_SNOW,
            RALLY_SQUARE,
            RALLY_START_RECORDING_STAGE_NOTES,
            RALLY_TARMAC,
            RALLY_THEN,
            RALLY_THROUGH_GATE,
            RALLY_TIGHTENS,
            RALLY_TIGHTENS_BAD,
            RALLY_TIGHTENS_THEN_OPENS,
            RALLY_TIGHTENS_TO_1,
            RALLY_TIGHTENS_TO_2,
            RALLY_TIGHTENS_TO_3,
            RALLY_TIGHTENS_TO_4,
            RALLY_TIGHTENS_TO_5,
            RALLY_TIGHTENS_TO_HAIRPIN,
            TOGGLE_RALLY_RECCE_MODE,
            RALLY_TREE_INSIDE,
            RALLY_TREE_OUTSIDE,
            RALLY_TUNNEL,
            RALLY_TWISTY,
            RALLY_UPHILL,
            RALLY_WIDE_OUT,
            RALLY_WIDENS,
            REFRESH_CHART,
            REPEAT_LAST_MESSAGE,
            RIVAL__,
            SESSION_STATUS,
            SET_ALARM_CLOCK,
            SET_FUEL_STRATEGY_CAUTIOUS,
            SET_FUEL_STRATEGY_RESET,
            SET_FUEL_STRATEGY_RISKY,
            SHOW_All_OVERLAYS,
            SHOW_CHART,
            SHOW_CONSOLE,
            SHOW_DISTANCE,
            SHOW_OVERLAY,
            SHOW_SINGLE_CHART,
            SHOW_STACKED_CHARTS,
            SHOW_SUBTITLES,
            SHOW_TIME,
            SHOW_VR_SETTING,
            SETUP_ADVISOR_WHATS_WRONG,
            SETUP_ADVISOR_SUGGEST_CHANGES,
            SETUP_ADVISOR_RUN_OPTIMIZER,
            SETUP_ADVISOR_HOW_AM_I_DOING,
            START_PACE_NOTES_PLAYBACK,
            STATUS,
            STOP_COMPLAINING,
            STOP_PACE_NOTES_PLAYBACK,
            STOP_WATCHING_ALL,
            STOP_WATCHING__,
            TALK_TO_ME_ANYWHERE,
            TELL_ME_THE_GAPS,
            TEAM_MATE__,
            TOGGLE_VR_OVERLAYS,
            VOIP_QUIETER,
            VOIP_LOUDER,
            WATCH_BEHIND_IN_THE_RACE,
            WATCH_IN_FRONT_IN_THE_RACE,
            WATCH__,
            WHAT_ARE_MY_BRAKE_TEMPS,
            WHAT_ARE_MY_ENGINE_TEMPS,
            WHAT_ARE_MY_LEFT_FRONT_SURFACE_TEMPS,
            WHAT_ARE_MY_LEFT_REAR_SURFACE_TEMPS,
            WHAT_ARE_MY_RIGHT_FRONT_SURFACE_TEMPS,
            WHAT_ARE_MY_RIGHT_REAR_SURFACE_TEMPS,
            WHAT_ARE_MY_SECTOR_TIMES,
            WHAT_ARE_MY_TYRE_PRESSURES,
            WHAT_ARE_MY_TYRE_TEMPS,
            WHAT_ARE_THE_PIT_ACTIONS,
            WHAT_ARE_THE_RELATIVE_TYRE_PERFORMANCES,
            WHAT_CLASS_IS_CAR_AHEAD,
            WHAT_CLASS_IS_CAR_BEHIND,
            WHAT_IS_MY_OIL_TEMP,
            WHAT_IS_MY_WATER_TEMP,
            WHAT_LAP_AM_I_ON,
            WHAT_TYRES_AM_I_ON,
            WHAT_TYRE_IS__,
            WHAT_TYRES_IS__,
            WHAT_WAS_MY_LAST_LAP_TIME,
            WHATS_MY_BEST_LAP_TIME,
            WHATS_MY_CAR_NUMBER,
            WHATS_MY_EXPECTED_FINISH_POSITION,
            WHATS_MY_FUEL_LEVEL,
            WHATS_MY_FUEL_USAGE,
            WHATS_MY_GAP_BEHIND,
            WHATS_MY_GAP_BEHIND_ON_TRACK,
            WHATS_MY_GAP_IN_FRONT,
            WHATS_MY_GAP_IN_FRONT_ON_TRACK,
            WHATS_MY_GAP_TO_LEADER,
            WHATS_MY_IRATING,
            WHATS_MY_LAST_SECTOR_TIME,
            WHATS_MY_LICENSE_CLASS,
            WHATS_MY_POSITION,
            WHATS_MY_RANK,
            WHATS_MY_RATING,
            WHATS_MY_REPUTATION,
            WHATS_PITLANE_SPEED_LIMIT,
            WHATS_THE_AIR_TEMP,
            WHATS_THE_FASTEST_LAP_TIME,
            WHATS_THE_INCIDENT_LIMIT,
            WHATS_THE_LEADER_LAP,
            WHATS_THE_SOF,
            WHATS_THE_TIME,
            WHATS_THE_TRACK_TEMP,
            WHATS_MY_BRAKE_BIAS,
            WHEN_DID_IN_FRONT_ON_TRACK_PIT,
            WHEN_DID_BEHIND_ON_TRACK_PIT,
            WHERE_AM_I_FASTER,
            WHERE_AM_I_SLOWER,
            WHERE_SHOULD_I_LINE_UP,
            WHOS_BEHIND_IN_THE_RACE,
            WHOS_BEHIND_ON_TRACK,
            WHOS_IN_FRONT_IN_THE_RACE,
            WHOS_IN_FRONT_ON_TRACK,
            WHOS_IN__,
            WHERE_IS__,
            WHERES__,
            WHATS__LAST_LAP,
            WHATS__LAST_LAP_TIME,
            WHATS__BEST_LAP,
            WHATS__BEST_LAP_TIME,
            WHATS__LICENSE_CLASS,
            WHATS__IRATING,
            WHATS__REPUTATION,
            WHATS__RATING,
            WHATS__RANK,
            WHOS_LEADING,
            WHOS_TWO_IN_FRONT_IN_THE_RACE,

            // built in controller button functions:
            ADD_TRACK_LANDMARK,
            CHANNEL_OPEN_FUNCTION,
            GET_CAR_STATUS,
            GET_DAMAGE_REPORT,
            GET_FUEL_STATUS,
            GET_SESSION_STATUS,
            GET_STATUS,
            PIT_PREDICTION,
            PRINT_TRACK_DATA,
            READ_CORNER_NAMES_FOR_LAP,
            REPEAT_LAST_MESSAGE_BUTTON,
            RESET_VR_VIEW,
            TOGGLE_BLOCK_MESSAGES_IN_HARD_PARTS,
            TOGGLE_ENABLE_CUT_TRACK_WARNINGS,
            TOGGLE_MANUAL_FORMATION_LAP,
            TOGGLE_MUTE,
            TOGGLE_PACE_NOTES_PLAYBACK,
            TOGGLE_PACE_NOTES_RECORDING,
            TOGGLE_RACE_UPDATES_FUNCTION,
            TOGGLE_READ_OPPONENT_DELTAS,
            TOGGLE_SPOTTER_FUNCTION,
            TOGGLE_TRACK_LANDMARKS_RECORDING,
            TOGGLE_YELLOW_FLAG_MESSAGES,
            VOLUME_DOWN,
            VOLUME_UP,

            NO_COMMAND
        }

        /// <summary>
        /// Dictionary of SpeechCommand identifiers and their corresponding
        /// speech strings
        /// </summary>
        private static readonly Dictionary<ID, string[]> speechCommands = new Dictionary<ID, string[]>
        {
            {ID.CALCULATE_FUEL_FOR,                        SpeechRecogniser.CALCULATE_FUEL_FOR},
            {ID.CAR_STATUS,                                SpeechRecogniser.CAR_STATUS},
            {ID.CHART_COMMAND_ADD,                         SpeechRecogniser.CHART_COMMAND_ADD},
            {ID.CHART_COMMAND_BEST_LAP,                    SpeechRecogniser.CHART_COMMAND_BEST_LAP},
            {ID.CHART_COMMAND_OPPONENT_BEST_LAP,           SpeechRecogniser.CHART_COMMAND_OPPONENT_BEST_LAP},
            {ID.CHART_COMMAND_PAN_LEFT,                    SpeechRecogniser.CHART_COMMAND_PAN_LEFT},
            {ID.CHART_COMMAND_PAN_RIGHT,                   SpeechRecogniser.CHART_COMMAND_PAN_RIGHT},
            {ID.CHART_COMMAND_REMOVE,                      SpeechRecogniser.CHART_COMMAND_REMOVE},
            {ID.CHART_COMMAND_RESET_ZOOM,                  SpeechRecogniser.CHART_COMMAND_RESET_ZOOM},
            {ID.CHART_COMMAND_SHOW_ALL_SECTORS,            SpeechRecogniser.CHART_COMMAND_SHOW_ALL_SECTORS},
            {ID.CHART_COMMAND_SHOW_LAST_LAP,               SpeechRecogniser.CHART_COMMAND_SHOW_LAST_LAP},
            {ID.CHART_COMMAND_SHOW_NEXT_LAP,               SpeechRecogniser.CHART_COMMAND_SHOW_NEXT_LAP},
            {ID.CHART_COMMAND_SHOW_PREVIOUS_LAP,           SpeechRecogniser.CHART_COMMAND_SHOW_PREVIOUS_LAP},
            {ID.CHART_COMMAND_SHOW_SECTOR_1,               SpeechRecogniser.CHART_COMMAND_SHOW_SECTOR_1},
            {ID.CHART_COMMAND_SHOW_SECTOR_2,               SpeechRecogniser.CHART_COMMAND_SHOW_SECTOR_2},
            {ID.CHART_COMMAND_SHOW_SECTOR_3,               SpeechRecogniser.CHART_COMMAND_SHOW_SECTOR_3},
            {ID.CHART_COMMAND_ZOOM_IN,                     SpeechRecogniser.CHART_COMMAND_ZOOM_IN},
            {ID.CHART_COMMAND_ZOOM_OUT,                    SpeechRecogniser.CHART_COMMAND_ZOOM_OUT},
            {ID.CLEAR_ALARM_CLOCK,                         SpeechRecogniser.CLEAR_ALARM_CLOCK},
            {ID.CLEAR_CHART,                               SpeechRecogniser.CLEAR_CHART},
            {ID.CLEAR_DATA,                                SpeechRecogniser.CLEAR_DATA},
            {ID.DAMAGE_REPORT,                             SpeechRecogniser.DAMAGE_REPORT},
            {ID.DISABLE_CUT_TRACK_WARNINGS,                SpeechRecogniser.DISABLE_CUT_TRACK_WARNINGS},
            {ID.DISABLE_MANUAL_FORMATION_LAP,              SpeechRecogniser.DISABLE_MANUAL_FORMATION_LAP},
            {ID.DISABLE_YELLOW_FLAG_MESSAGES,              SpeechRecogniser.DISABLE_YELLOW_FLAG_MESSAGES},
            {ID.DO_I_HAVE_A_PENALTY,                       SpeechRecogniser.DO_I_HAVE_A_PENALTY},
            {ID.DO_I_HAVE_A_MANDATORY_PIT_STOP,            SpeechRecogniser.DO_I_HAVE_A_MANDATORY_PIT_STOP},
            {ID.DO_I_STILL_HAVE_A_PENALTY,                 SpeechRecogniser.DO_I_STILL_HAVE_A_PENALTY},
            {ID.DONT_TALK_IN_THE_CORNERS,                  SpeechRecogniser.DONT_TALK_IN_THE_CORNERS},
            {ID.DONT_TELL_ME_THE_GAPS,                     SpeechRecogniser.DONT_TELL_ME_THE_GAPS},
            {ID.ENABLE_CUT_TRACK_WARNINGS,                 SpeechRecogniser.ENABLE_CUT_TRACK_WARNINGS},
            {ID.ENABLE_MANUAL_FORMATION_LAP,               SpeechRecogniser.ENABLE_MANUAL_FORMATION_LAP},
            {ID.ENABLE_YELLOW_FLAG_MESSAGES,               SpeechRecogniser.ENABLE_YELLOW_FLAG_MESSAGES},
            {ID.GALLONS,                                   SpeechRecogniser.GALLONS},
            {ID.GAME_QUIETER,                              SpeechRecogniser.GAME_QUIETER},
            {ID.GAME_LOUDER,                               SpeechRecogniser.GAME_LOUDER},
            {ID.HAVE_I_SERVED_MY_PENALTY,                  SpeechRecogniser.HAVE_I_SERVED_MY_PENALTY},
            {ID.HIDE_CHART,                                SpeechRecogniser.HIDE_CHART},
            {ID.HIDE_CONSOLE,                              SpeechRecogniser.HIDE_CONSOLE},
            {ID.HIDE_OVERLAY,                              SpeechRecogniser.HIDE_OVERLAY},
            {ID.HIDE_SUBTITLES,                            SpeechRecogniser.HIDE_SUBTITLES},
            {ID.HIDE_VR_SETTING,                           SpeechRecogniser.HIDE_VR_SETTING},
            {ID.HOURS,                                     SpeechRecogniser.HOURS},
            {ID.HOW_ARE_MY_BRAKE_TEMPS,                    SpeechRecogniser.HOW_ARE_MY_BRAKE_TEMPS},
            {ID.HOW_ARE_MY_ENGINE_TEMPS,                   SpeechRecogniser.HOW_ARE_MY_ENGINE_TEMPS},
            {ID.HOW_ARE_MY_FRONT_TYRE_PRESSURES,           SpeechRecogniser.HOW_ARE_MY_FRONT_TYRE_PRESSURES},
            {ID.HOW_ARE_MY_FRONT_TYRE_PRESSURES_RIGHT_NOW, SpeechRecogniser.HOW_ARE_MY_FRONT_TYRE_PRESSURES_RIGHT_NOW},
            {ID.HOW_ARE_MY_REAR_TYRE_PRESSURES,            SpeechRecogniser.HOW_ARE_MY_REAR_TYRE_PRESSURES},
            {ID.HOW_ARE_MY_REAR_TYRE_PRESSURES_RIGHT_NOW,  SpeechRecogniser.HOW_ARE_MY_REAR_TYRE_PRESSURES_RIGHT_NOW},
            {ID.HOW_ARE_MY_TYRE_PRESSURES,                 SpeechRecogniser.HOW_ARE_MY_TYRE_PRESSURES},
            {ID.HOW_ARE_MY_TYRE_PRESSURES_RIGHT_NOW,       SpeechRecogniser.HOW_ARE_MY_TYRE_PRESSURES_RIGHT_NOW},
            {ID.HOW_ARE_MY_TYRE_TEMPS,                     SpeechRecogniser.HOW_ARE_MY_TYRE_TEMPS},
            {ID.HOW_GOOD_IS,                               SpeechRecogniser.HOW_GOOD_IS},
            {ID.HOW_LONG_WILL_THESE_TYRES_LAST,            SpeechRecogniser.HOW_LONG_WILL_THESE_TYRES_LAST},
            {ID.HOW_LONGS_LEFT,                            SpeechRecogniser.HOW_LONGS_LEFT},
            {ID.HOW_MANY_DRS_ACTIVATIONS_LEFT,             SpeechRecogniser.HOW_MANY_DRS_ACTIVATIONS_LEFT },
            {ID.HOW_MANY_INCIDENT_POINTS,                  SpeechRecogniser.HOW_MANY_INCIDENT_POINTS},
            {ID.HOW_MANY_LAPS_ON_TYRE_SET,                 SpeechRecogniser.HOW_MANY_LAPS_ON_TYRE_SET},
            {ID.HOW_MANY_LAPS_SINCE_PITTING,               SpeechRecogniser.HOW_MANY_LAPS_SINCE_PITTING},
            {ID.HOW_MUCH_FUEL_TO_END_OF_RACE,              SpeechRecogniser.HOW_MUCH_FUEL_TO_END_OF_RACE},
            {ID.HOW_OLD_ARE_THESE_TYRES,                   SpeechRecogniser.HOW_OLD_ARE_THESE_TYRES},
            {ID.HOWS_MY_AERO,                              SpeechRecogniser.HOWS_MY_AERO},
            {ID.HOWS_MY_BATTERY,                           SpeechRecogniser.HOWS_MY_BATTERY},
            {ID.HOWS_MY_BRAKES,                            SpeechRecogniser.HOWS_MY_BRAKES},
            {ID.HOWS_MY_ENGINE,                            SpeechRecogniser.HOWS_MY_ENGINE},
            {ID.HOWS_MY_FRONT_CAMBER,                      SpeechRecogniser.HOWS_MY_FRONT_CAMBER},
            {ID.HOWS_MY_FRONT_CAMBER_RIGHT_NOW,            SpeechRecogniser.HOWS_MY_FRONT_CAMBER_RIGHT_NOW},
            {ID.HOWS_MY_FUEL,                              SpeechRecogniser.HOWS_MY_FUEL},
            {ID.SETUP_ADVISOR_WHATS_WRONG,                 SpeechRecogniser.SETUP_ADVISOR_WHATS_WRONG},
            {ID.SETUP_ADVISOR_SUGGEST_CHANGES,             SpeechRecogniser.SETUP_ADVISOR_SUGGEST_CHANGES},
            {ID.SETUP_ADVISOR_RUN_OPTIMIZER,               SpeechRecogniser.SETUP_ADVISOR_RUN_OPTIMIZER},
            {ID.SETUP_ADVISOR_HOW_AM_I_DOING,              SpeechRecogniser.SETUP_ADVISOR_HOW_AM_I_DOING},
            {ID.HOWS_MY_LEFT_FRONT_CAMBER,                 SpeechRecogniser.HOWS_MY_LEFT_FRONT_CAMBER},
            {ID.HOWS_MY_LEFT_FRONT_CAMBER_RIGHT_NOW,       SpeechRecogniser.HOWS_MY_LEFT_FRONT_CAMBER_RIGHT_NOW},
            {ID.HOWS_MY_LEFT_REAR_CAMBER,                  SpeechRecogniser.HOWS_MY_LEFT_REAR_CAMBER},
            {ID.HOWS_MY_LEFT_REAR_CAMBER_RIGHT_NOW,        SpeechRecogniser.HOWS_MY_LEFT_REAR_CAMBER_RIGHT_NOW},
            {ID.HOWS_MY_PACE,                              SpeechRecogniser.HOWS_MY_PACE},
            {ID.HOWS_MY_REAR_CAMBER,                       SpeechRecogniser.HOWS_MY_REAR_CAMBER},
            {ID.HOWS_MY_REAR_CAMBER_RIGHT_NOW,             SpeechRecogniser.HOWS_MY_REAR_CAMBER_RIGHT_NOW},
            {ID.HOWS_MY_RIGHT_FRONT_CAMBER,                SpeechRecogniser.HOWS_MY_RIGHT_FRONT_CAMBER},
            {ID.HOWS_MY_RIGHT_FRONT_CAMBER_RIGHT_NOW,      SpeechRecogniser.HOWS_MY_RIGHT_FRONT_CAMBER_RIGHT_NOW},
            {ID.HOWS_MY_RIGHT_REAR_CAMBER,                 SpeechRecogniser.HOWS_MY_RIGHT_REAR_CAMBER},
            {ID.HOWS_MY_RIGHT_REAR_CAMBER_RIGHT_NOW,       SpeechRecogniser.HOWS_MY_RIGHT_REAR_CAMBER_RIGHT_NOW},
            {ID.HOWS_MY_SELF_PACE,                         SpeechRecogniser.HOWS_MY_SELF_PACE},
            {ID.HOWS_MY_SUSPENSION,                        SpeechRecogniser.HOWS_MY_SUSPENSION},
            {ID.HOWS_MY_TRANSMISSION,                      SpeechRecogniser.HOWS_MY_TRANSMISSION},
            {ID.HOWS_MY_TYRE_WEAR,                         SpeechRecogniser.HOWS_MY_TYRE_WEAR},
            {ID.IS_CAR_AHEAD_MY_CLASS,                     SpeechRecogniser.IS_CAR_AHEAD_MY_CLASS},
            {ID.IS_CAR_BEHIND_MY_CLASS,                    SpeechRecogniser.IS_CAR_BEHIND_MY_CLASS},
            {ID.IS_MY_PIT_BOX_OCCUPIED,                    SpeechRecogniser.IS_MY_PIT_BOX_OCCUPIED},
            {ID.KEEP_ME_INFORMED,                          SpeechRecogniser.KEEP_ME_INFORMED},
            {ID.KEEP_QUIET,                                SpeechRecogniser.KEEP_QUIET},
            {ID.NOTE_BAD_DRIVER_AHEAD_ON_TRACK,            SpeechRecogniser.NOTE_BAD_DRIVER_AHEAD_ON_TRACK},
            {ID.NOTE_BAD_DRIVER_BEHIND_ON_TRACK,           SpeechRecogniser.NOTE_BAD_DRIVER_BEHIND_ON_TRACK},
            {ID.PIT_STOP_ADD,                              SpeechRecogniser.PIT_STOP_ADD},
            {ID.PIT_STOP_ALTERNATE_TYRES,                  SpeechRecogniser.PIT_STOP_ALTERNATE_TYRES},
            {ID.PIT_STOP_CHANGE_ALL_TYRES,                 SpeechRecogniser.PIT_STOP_CHANGE_ALL_TYRES},
            {ID.PIT_STOP_CHANGE_FRONT_LEFT_TYRE,           SpeechRecogniser.PIT_STOP_CHANGE_FRONT_LEFT_TYRE},
            {ID.PIT_STOP_CHANGE_FRONT_LEFT_TYRE_PRESSURE,  SpeechRecogniser.PIT_STOP_CHANGE_FRONT_LEFT_TYRE_PRESSURE},
            {ID.PIT_STOP_CHANGE_FRONT_PRESSURES,           SpeechRecogniser.PIT_STOP_CHANGE_FRONT_PRESSURES},
            {ID.PIT_STOP_CHANGE_FRONT_RIGHT_TYRE,          SpeechRecogniser.PIT_STOP_CHANGE_FRONT_RIGHT_TYRE},
            {ID.PIT_STOP_CHANGE_FRONT_RIGHT_TYRE_PRESSURE, SpeechRecogniser.PIT_STOP_CHANGE_FRONT_RIGHT_TYRE_PRESSURE},
            {ID.PIT_STOP_CHANGE_FRONT_TYRES,               SpeechRecogniser.PIT_STOP_CHANGE_FRONT_TYRES},
            {ID.PIT_STOP_CHANGE_LEFT_SIDE_TYRES,           SpeechRecogniser.PIT_STOP_CHANGE_LEFT_SIDE_TYRES},
            {ID.PIT_STOP_CHANGE_REAR_LEFT_TYRE,            SpeechRecogniser.PIT_STOP_CHANGE_REAR_LEFT_TYRE},
            {ID.PIT_STOP_CHANGE_REAR_LEFT_TYRE_PRESSURE,   SpeechRecogniser.PIT_STOP_CHANGE_REAR_LEFT_TYRE_PRESSURE},
            {ID.PIT_STOP_CHANGE_REAR_PRESSURES,            SpeechRecogniser.PIT_STOP_CHANGE_REAR_PRESSURES},
            {ID.PIT_STOP_CHANGE_REAR_RIGHT_TYRE,           SpeechRecogniser.PIT_STOP_CHANGE_REAR_RIGHT_TYRE},
            {ID.PIT_STOP_CHANGE_REAR_RIGHT_TYRE_PRESSURE,  SpeechRecogniser.PIT_STOP_CHANGE_REAR_RIGHT_TYRE_PRESSURE},
            {ID.PIT_STOP_CHANGE_REAR_TYRES,                SpeechRecogniser.PIT_STOP_CHANGE_REAR_TYRES},
            {ID.PIT_STOP_CHANGE_RIGHT_SIDE_TYRES,          SpeechRecogniser.PIT_STOP_CHANGE_RIGHT_SIDE_TYRES},
            {ID.PIT_STOP_CHANGE_TYRE_PRESSURE,             SpeechRecogniser.PIT_STOP_CHANGE_TYRE_PRESSURE},
            {ID.PIT_STOP_CHANGE_TYRES,                     SpeechRecogniser.PIT_STOP_CHANGE_TYRES},
            {ID.PIT_STOP_CLEAR_ALL,                        SpeechRecogniser.PIT_STOP_CLEAR_ALL},
            {ID.PIT_STOP_CLEAR_FAST_REPAIR,                SpeechRecogniser.PIT_STOP_CLEAR_FAST_REPAIR},
            {ID.PIT_STOP_CLEAR_FUEL,                       SpeechRecogniser.PIT_STOP_CLEAR_FUEL},
            {ID.PIT_STOP_CLEAR_TYRES,                      SpeechRecogniser.PIT_STOP_CLEAR_TYRES},
            {ID.PIT_STOP_CLEAR_WIND_SCREEN,                SpeechRecogniser.PIT_STOP_CLEAR_WIND_SCREEN},
            {ID.PIT_STOP_DONT_FIX_SUSPENSION,              SpeechRecogniser.PIT_STOP_DONT_FIX_SUSPENSION},
            {ID.PIT_STOP_DONT_REFUEL,                      SpeechRecogniser.PIT_STOP_DONT_REFUEL},
            {ID.PIT_STOP_DONT_SERVE_PENALTY,               SpeechRecogniser.PIT_STOP_DONT_SERVE_PENALTY},
            {ID.PIT_STOP_DRY_TYRES,                        SpeechRecogniser.PIT_STOP_DRY_TYRES},
            {ID.PIT_STOP_FAST_REPAIR,                      SpeechRecogniser.PIT_STOP_FAST_REPAIR},
            {ID.PIT_STOP_FIX_ALL,                          SpeechRecogniser.PIT_STOP_FIX_ALL},
            {ID.PIT_STOP_FIX_ALL_AERO,                     SpeechRecogniser.PIT_STOP_FIX_ALL_AERO},
            {ID.PIT_STOP_FIX_BODY,                         SpeechRecogniser.PIT_STOP_FIX_BODY},
            {ID.PIT_STOP_FIX_FRONT_AERO,                   SpeechRecogniser.PIT_STOP_FIX_FRONT_AERO},
            {ID.PIT_STOP_FIX_NO_AERO,                      SpeechRecogniser.PIT_STOP_FIX_NO_AERO},
            {ID.PIT_STOP_FIX_NONE,                         SpeechRecogniser.PIT_STOP_FIX_NONE},
            {ID.PIT_STOP_FIX_REAR_AERO,                    SpeechRecogniser.PIT_STOP_FIX_REAR_AERO},
            {ID.PIT_STOP_FIX_SUSPENSION,                   SpeechRecogniser.PIT_STOP_FIX_SUSPENSION},
            {ID.PIT_STOP_FUEL_TO_THE_END,                  SpeechRecogniser.PIT_STOP_FUEL_TO_THE_END},
            {ID.PIT_STOP_FUEL_RATIO,                       SpeechRecogniser.PIT_STOP_FUEL_RATIO},
            {ID.PIT_STOP_VIRTUAL_ENERGY,                   SpeechRecogniser.PIT_STOP_VIRTUAL_ENERGY},
            {ID.PIT_STOP_HARD_TYRES,                       SpeechRecogniser.PIT_STOP_HARD_TYRES},
            {ID.PIT_STOP_MEDIUM_TYRES,                     SpeechRecogniser.PIT_STOP_MEDIUM_TYRES},
            {ID.PIT_STOP_NEXT_TYRE_COMPOUND,               SpeechRecogniser.PIT_STOP_NEXT_TYRE_COMPOUND},
            {ID.PIT_STOP_OPTION_TYRES,                     SpeechRecogniser.PIT_STOP_OPTION_TYRES},
            {ID.PIT_STOP_PRIME_TYRES,                      SpeechRecogniser.PIT_STOP_PRIME_TYRES},
            {ID.PIT_STOP_REFUEL,                           SpeechRecogniser.PIT_STOP_REFUEL},
            {ID.PIT_STOP_SELECT_LEAST_USED_TYRE_SET,       SpeechRecogniser.PIT_STOP_SELECT_LEAST_USED_TYRE_SET},
            {ID.PIT_STOP_SELECT_TYRE_SET,                  SpeechRecogniser.PIT_STOP_SELECT_TYRE_SET},
            {ID.PIT_STOP_SERVE_PENALTY,                    SpeechRecogniser.PIT_STOP_SERVE_PENALTY},
            {ID.PIT_STOP_SOFT_TYRES,                       SpeechRecogniser.PIT_STOP_SOFT_TYRES},
            {ID.PIT_STOP_SUPERSOFT_TYRES,                  SpeechRecogniser.PIT_STOP_SUPERSOFT_TYRES},
            {ID.PIT_STOP_TEAROFF,                          SpeechRecogniser.PIT_STOP_TEAROFF},
            {ID.PIT_STOP_WET_TYRES,                        SpeechRecogniser.PIT_STOP_WET_TYRES},
            {ID.PIT_STOP_USED_HARD_TYRES,                  SpeechRecogniser.PIT_STOP_USED_HARD_TYRES},
            {ID.PIT_STOP_USED_MEDIUM_TYRES,                SpeechRecogniser.PIT_STOP_USED_MEDIUM_TYRES},
            {ID.PIT_STOP_USED_SOFT_TYRES,                  SpeechRecogniser.PIT_STOP_USED_SOFT_TYRES},
            {ID.PLAY_CORNER_NAMES,                         SpeechRecogniser.PLAY_CORNER_NAMES},
            {ID.PLAY_POST_PIT_POSITION_ESTIMATE,           SpeechRecogniser.PLAY_POST_PIT_POSITION_ESTIMATE},
            {ID.PRACTICE_PIT_STOP,                         SpeechRecogniser.PRACTICE_PIT_STOP},
            {ID.RADIO_CHECK,                               SpeechRecogniser.RADIO_CHECK},
            {ID.RALLY_1,                                   SpeechRecogniser.RALLY_1},
            {ID.RALLY_2,                                   SpeechRecogniser.RALLY_2},
            {ID.RALLY_3,                                   SpeechRecogniser.RALLY_3},
            {ID.RALLY_4,                                   SpeechRecogniser.RALLY_4},
            {ID.RALLY_5,                                   SpeechRecogniser.RALLY_5},
            {ID.RALLY_6,                                   SpeechRecogniser.RALLY_6},
            {ID.RALLY_AND,                                 SpeechRecogniser.RALLY_AND},
            {ID.RALLY_BAD_CAMBER,                          SpeechRecogniser.RALLY_BAD_CAMBER},
            {ID.RALLY_BIG_JUMP,                            SpeechRecogniser.RALLY_BIG_JUMP},
            {ID.RALLY_BRAKE,                               SpeechRecogniser.RALLY_BRAKE},
            {ID.RALLY_BRIDGE,                              SpeechRecogniser.RALLY_BRIDGE},
            {ID.RALLY_BUMPS,                               SpeechRecogniser.RALLY_BUMPS},
            {ID.RALLY_CARE,                                SpeechRecogniser.RALLY_CARE},
            {ID.RALLY_CAUTION,                             SpeechRecogniser.RALLY_CAUTION},
            {ID.RALLY_CONCRETE,                            SpeechRecogniser.RALLY_CONCRETE},
            {ID.RALLY_CORNER_DECRIPTIONS,                  SpeechRecogniser.RALLY_CORNER_DECRIPTIONS},
            {ID.RALLY_CORNER_DIRECTION_FIRST,              SpeechRecogniser.RALLY_CORNER_DIRECTION_FIRST},
            {ID.RALLY_CORNER_NUMBER_FIRST,                 SpeechRecogniser.RALLY_CORNER_NUMBER_FIRST},
            {ID.RALLY_CORRECTION,                          SpeechRecogniser.RALLY_CORRECTION},
            {ID.RALLY_CREST,                               SpeechRecogniser.RALLY_CREST},
            {ID.RALLY_CUT,                                 SpeechRecogniser.RALLY_CUT},
            {ID.RALLY_DANGER,                              SpeechRecogniser.RALLY_DANGER},
            {ID.RALLY_DEEP_RUTS,                           SpeechRecogniser.RALLY_DEEP_RUTS},
            {ID.RALLY_DIP,                                 SpeechRecogniser.RALLY_DIP},
            {ID.RALLY_DISTANCE,                            SpeechRecogniser.RALLY_DISTANCE},
            {ID.RALLY_DONT_CUT,                            SpeechRecogniser.RALLY_DONT_CUT},
            {ID.RALLY_DOUBLE_CAUTION,                      SpeechRecogniser.RALLY_DOUBLE_CAUTION},
            {ID.RALLY_DOWNHILL,                            SpeechRecogniser.RALLY_DOWNHILL},
            {ID.RALLY_EARLIER,                             SpeechRecogniser.RALLY_EARLIER},
            {ID.RALLY_EARLIER_CALLS,                       SpeechRecogniser.RALLY_EARLIER_CALLS},
            {ID.RALLY_FINISH_RECORDING_STAGE_NOTES,        SpeechRecogniser.RALLY_FINISH_RECORDING_STAGE_NOTES},
            {ID.RALLY_FLAT,                                SpeechRecogniser.RALLY_FLAT},
            {ID.RALLY_FORD,                                SpeechRecogniser.RALLY_FORD},
            {ID.RALLY_GO_STRAIGHT,                         SpeechRecogniser.RALLY_GO_STRAIGHT},
            {ID.RALLY_GRAVEL,                              SpeechRecogniser.RALLY_GRAVEL},
            {ID.RALLY_HAIRPIN,                             SpeechRecogniser.RALLY_HAIRPIN},
            {ID.RALLY_INSERT,                              SpeechRecogniser.RALLY_INSERT},
            {ID.RALLY_INTO,                                SpeechRecogniser.RALLY_INTO},
            {ID.RALLY_JUMP,                                SpeechRecogniser.RALLY_JUMP},
            {ID.RALLY_JUNCTION,                            SpeechRecogniser.RALLY_JUNCTION},
            {ID.RALLY_KEEP_IN,                             SpeechRecogniser.RALLY_KEEP_IN},
            {ID.RALLY_KEEP_LEFT,                           SpeechRecogniser.RALLY_KEEP_LEFT},
            {ID.RALLY_KEEP_MIDDLE,                         SpeechRecogniser.RALLY_KEEP_MIDDLE},
            {ID.RALLY_KEEP_OUT,                            SpeechRecogniser.RALLY_KEEP_OUT},
            {ID.RALLY_KEEP_RIGHT,                          SpeechRecogniser.RALLY_KEEP_RIGHT},
            {ID.RALLY_LATER,                               SpeechRecogniser.RALLY_LATER},
            {ID.RALLY_LATER_CALLS,                         SpeechRecogniser.RALLY_LATER_CALLS},
            {ID.RALLY_LEFT,                                SpeechRecogniser.RALLY_LEFT},
            {ID.RALLY_LEFT_ENTRY_CHICANE,                  SpeechRecogniser.RALLY_LEFT_ENTRY_CHICANE},
            {ID.RALLY_LOGS_INSIDE,                         SpeechRecogniser.RALLY_LOGS_INSIDE},
            {ID.RALLY_LOGS_OUTSIDE,                        SpeechRecogniser.RALLY_LOGS_OUTSIDE},
            {ID.RALLY_LONG,                                SpeechRecogniser.RALLY_LONG},
            {ID.RALLY_LONGLONG,                            SpeechRecogniser.RALLY_LONGLONG},
            {ID.RALLY_LOOSE_GRAVEL,                        SpeechRecogniser.RALLY_LOOSE_GRAVEL},
            {ID.RALLY_MAYBE,                               SpeechRecogniser.RALLY_MAYBE},
            {ID.RALLY_MINUS,                               SpeechRecogniser.RALLY_MINUS},
            {ID.RALLY_NARROWS,                             SpeechRecogniser.RALLY_NARROWS},
            {ID.RALLY_OPEN_HAIRPIN,                        SpeechRecogniser.RALLY_OPEN_HAIRPIN},
            {ID.RALLY_OPENS,                               SpeechRecogniser.RALLY_OPENS},
            {ID.RALLY_OPENS_THEN_TIGHTENS,                 SpeechRecogniser.RALLY_OPENS_THEN_TIGHTENS},
            {ID.RALLY_OVER_BRIDGE,                         SpeechRecogniser.RALLY_OVER_BRIDGE},
            {ID.RALLY_OVER_CREST,                          SpeechRecogniser.RALLY_OVER_CREST},
            {ID.RALLY_OVER_JUMP,                           SpeechRecogniser.RALLY_OVER_JUMP},
            {ID.RALLY_OVER_RAILS,                          SpeechRecogniser.RALLY_OVER_RAILS},
            {ID.RALLY_PLUS,                                SpeechRecogniser.RALLY_PLUS},
            {ID.RALLY_RIGHT,                               SpeechRecogniser.RALLY_RIGHT},
            {ID.RALLY_RIGHT_ENTRY_CHICANE,                 SpeechRecogniser.RALLY_RIGHT_ENTRY_CHICANE},
            {ID.RALLY_ROCKS_INSIDE,                        SpeechRecogniser.RALLY_ROCKS_INSIDE},
            {ID.RALLY_ROCKS_OUTSIDE,                       SpeechRecogniser.RALLY_ROCKS_OUTSIDE},
            {ID.RALLY_RUTS,                                SpeechRecogniser.RALLY_RUTS},
            {ID.RALLY_SLIPPY,                              SpeechRecogniser.RALLY_SLIPPY},
            {ID.RALLY_SNOW,                                SpeechRecogniser.RALLY_SNOW},
            {ID.RALLY_SQUARE,                              SpeechRecogniser.RALLY_SQUARE},
            {ID.RALLY_START_RECORDING_STAGE_NOTES,         SpeechRecogniser.RALLY_START_RECORDING_STAGE_NOTES},
            {ID.RALLY_TARMAC,                              SpeechRecogniser.RALLY_TARMAC},
            {ID.RALLY_THEN,                                SpeechRecogniser.RALLY_THEN},
            {ID.RALLY_THROUGH_GATE,                        SpeechRecogniser.RALLY_THROUGH_GATE},
            {ID.RALLY_TIGHTENS,                            SpeechRecogniser.RALLY_TIGHTENS},
            {ID.RALLY_TIGHTENS_BAD,                        SpeechRecogniser.RALLY_TIGHTENS_BAD},
            {ID.RALLY_TIGHTENS_THEN_OPENS,                 SpeechRecogniser.RALLY_TIGHTENS_THEN_OPENS},
            {ID.RALLY_TIGHTENS_TO_1,                       SpeechRecogniser.RALLY_TIGHTENS_TO_1},
            {ID.RALLY_TIGHTENS_TO_2,                       SpeechRecogniser.RALLY_TIGHTENS_TO_2},
            {ID.RALLY_TIGHTENS_TO_3,                       SpeechRecogniser.RALLY_TIGHTENS_TO_3},
            {ID.RALLY_TIGHTENS_TO_4,                       SpeechRecogniser.RALLY_TIGHTENS_TO_4},
            {ID.RALLY_TIGHTENS_TO_5,                       SpeechRecogniser.RALLY_TIGHTENS_TO_5},
            {ID.RALLY_TIGHTENS_TO_HAIRPIN,                 SpeechRecogniser.RALLY_TIGHTENS_TO_HAIRPIN},
            {ID.RALLY_TREE_INSIDE,                         SpeechRecogniser.RALLY_TREE_INSIDE},
            {ID.RALLY_TREE_OUTSIDE,                        SpeechRecogniser.RALLY_TREE_OUTSIDE},
            {ID.RALLY_TUNNEL,                              SpeechRecogniser.RALLY_TUNNEL},
            {ID.RALLY_TWISTY,                              SpeechRecogniser.RALLY_TWISTY},
            {ID.RALLY_UPHILL,                              SpeechRecogniser.RALLY_UPHILL},
            {ID.RALLY_WIDE_OUT,                            SpeechRecogniser.RALLY_WIDE_OUT},
            {ID.RALLY_WIDENS,                              SpeechRecogniser.RALLY_WIDENS},
            {ID.REFRESH_CHART,                             SpeechRecogniser.REFRESH_CHART},
            {ID.REPEAT_LAST_MESSAGE,                       SpeechRecogniser.REPEAT_LAST_MESSAGE},
            {ID.RIVAL__,                                   new string[] {SpeechRecogniser.RIVAL} },
            {ID.SESSION_STATUS,                            SpeechRecogniser.SESSION_STATUS},
            {ID.SET_ALARM_CLOCK,                           SpeechRecogniser.SET_ALARM_CLOCK},
            {ID.SET_FUEL_STRATEGY_CAUTIOUS,                SpeechRecogniser.SET_FUEL_STRATEGY_CAUTIOUS},
            {ID.SET_FUEL_STRATEGY_RESET,                   SpeechRecogniser.SET_FUEL_STRATEGY_RESET},
            {ID.SET_FUEL_STRATEGY_RISKY,                   SpeechRecogniser.SET_FUEL_STRATEGY_RISKY},
            {ID.SHOW_All_OVERLAYS,                         SpeechRecogniser.SHOW_All_OVERLAYS},
            {ID.SHOW_CHART,                                SpeechRecogniser.SHOW_CHART},
            {ID.SHOW_CONSOLE,                              SpeechRecogniser.SHOW_CONSOLE},
            {ID.SHOW_DISTANCE,                             SpeechRecogniser.SHOW_DISTANCE},
            {ID.SHOW_OVERLAY,                              SpeechRecogniser.SHOW_OVERLAY},
            {ID.SHOW_SINGLE_CHART,                         SpeechRecogniser.SHOW_SINGLE_CHART},
            {ID.SHOW_STACKED_CHARTS,                       SpeechRecogniser.SHOW_STACKED_CHARTS},
            {ID.SHOW_SUBTITLES,                            SpeechRecogniser.SHOW_SUBTITLES},
            {ID.SHOW_TIME,                                 SpeechRecogniser.SHOW_TIME},
            {ID.SHOW_VR_SETTING,                           SpeechRecogniser.SHOW_VR_SETTING},
            {ID.START_PACE_NOTES_PLAYBACK,                 SpeechRecogniser.START_PACE_NOTES_PLAYBACK},
            {ID.STATUS,                                    SpeechRecogniser.STATUS},
            {ID.STOP_COMPLAINING,                          SpeechRecogniser.STOP_COMPLAINING},
            {ID.STOP_PACE_NOTES_PLAYBACK,                  SpeechRecogniser.STOP_PACE_NOTES_PLAYBACK},
            {ID.STOP_WATCHING_ALL,                         SpeechRecogniser.STOP_WATCHING_ALL},
            {ID.STOP_WATCHING__,                           new string[] {SpeechRecogniser.STOP_WATCHING} },
            {ID.TALK_TO_ME_ANYWHERE,                       SpeechRecogniser.TALK_TO_ME_ANYWHERE},
            {ID.TEAM_MATE__,                               new string[] {SpeechRecogniser.TEAM_MATE} },
            {ID.TELL_ME_THE_GAPS,                          SpeechRecogniser.TELL_ME_THE_GAPS},
            {ID.TOGGLE_VR_OVERLAYS,                        SpeechRecogniser.TOGGLE_VR_OVERLAYS},
            {ID.VOIP_QUIETER,                              SpeechRecogniser.VOIP_QUIETER},
            {ID.VOIP_LOUDER,                               SpeechRecogniser.VOIP_LOUDER},
            {ID.VOLUME_DOWN,                               SpeechRecogniser.CREW_CHIEF_QUIETER},
            {ID.VOLUME_UP,                                 SpeechRecogniser.CREW_CHIEF_LOUDER},
            {ID.WATCH_BEHIND_IN_THE_RACE,                  SpeechRecogniser.WATCH_BEHIND_IN_THE_RACE},
            {ID.WATCH_IN_FRONT_IN_THE_RACE,                SpeechRecogniser.WATCH_IN_FRONT_IN_THE_RACE},
            {ID.WATCH__,                                   new string[] {SpeechRecogniser.WATCH} },
            {ID.WHAT_ARE_MY_BRAKE_TEMPS,                   SpeechRecogniser.WHAT_ARE_MY_BRAKE_TEMPS},
            {ID.WHAT_ARE_MY_ENGINE_TEMPS,                  SpeechRecogniser.WHAT_ARE_MY_ENGINE_TEMPS},
            {ID.WHAT_ARE_MY_LEFT_FRONT_SURFACE_TEMPS,      SpeechRecogniser.WHAT_ARE_MY_LEFT_FRONT_SURFACE_TEMPS},
            {ID.WHAT_ARE_MY_LEFT_REAR_SURFACE_TEMPS,       SpeechRecogniser.WHAT_ARE_MY_LEFT_REAR_SURFACE_TEMPS},
            {ID.WHAT_ARE_MY_RIGHT_FRONT_SURFACE_TEMPS,     SpeechRecogniser.WHAT_ARE_MY_RIGHT_FRONT_SURFACE_TEMPS},
            {ID.WHAT_ARE_MY_RIGHT_REAR_SURFACE_TEMPS,      SpeechRecogniser.WHAT_ARE_MY_RIGHT_REAR_SURFACE_TEMPS},
            {ID.WHAT_ARE_MY_SECTOR_TIMES,                  SpeechRecogniser.WHAT_ARE_MY_SECTOR_TIMES},
            {ID.WHAT_ARE_MY_TYRE_PRESSURES,                SpeechRecogniser.WHAT_ARE_MY_TYRE_PRESSURES},
            {ID.WHAT_ARE_MY_TYRE_TEMPS,                    SpeechRecogniser.WHAT_ARE_MY_TYRE_TEMPS},
            {ID.WHAT_ARE_THE_PIT_ACTIONS,                  SpeechRecogniser.WHAT_ARE_THE_PIT_ACTIONS},
            {ID.WHAT_ARE_THE_RELATIVE_TYRE_PERFORMANCES,   SpeechRecogniser.WHAT_ARE_THE_RELATIVE_TYRE_PERFORMANCES},
            {ID.WHAT_CLASS_IS_CAR_AHEAD,                   SpeechRecogniser.WHAT_CLASS_IS_CAR_AHEAD},
            {ID.WHAT_CLASS_IS_CAR_BEHIND,                  SpeechRecogniser.WHAT_CLASS_IS_CAR_BEHIND},
            {ID.WHAT_IS_MY_OIL_TEMP,                       SpeechRecogniser.WHAT_IS_MY_OIL_TEMP},
            {ID.WHAT_IS_MY_WATER_TEMP,                     SpeechRecogniser.WHAT_IS_MY_WATER_TEMP},
            {ID.WHAT_LAP_AM_I_ON,                          SpeechRecogniser.WHAT_LAP_AM_I_ON},
            {ID.WHAT_TYRES_AM_I_ON,                        SpeechRecogniser.WHAT_TYRES_AM_I_ON},
            {ID.WHAT_WAS_MY_LAST_LAP_TIME,                 SpeechRecogniser.WHAT_WAS_MY_LAST_LAP_TIME},
            {ID.WHATS_MY_BEST_LAP_TIME,                    SpeechRecogniser.WHATS_MY_BEST_LAP_TIME},
            {ID.WHATS_MY_CAR_NUMBER,                       SpeechRecogniser.WHATS_MY_CAR_NUMBER},
            {ID.WHATS_MY_EXPECTED_FINISH_POSITION,         SpeechRecogniser.WHATS_MY_EXPECTED_FINISH_POSITION},
            {ID.WHATS_MY_FUEL_LEVEL,                       SpeechRecogniser.WHATS_MY_FUEL_LEVEL},
            {ID.WHATS_MY_FUEL_USAGE,                       SpeechRecogniser.WHATS_MY_FUEL_USAGE},
            {ID.WHATS_MY_GAP_BEHIND,                       SpeechRecogniser.WHATS_MY_GAP_BEHIND},
            {ID.WHATS_MY_GAP_BEHIND_ON_TRACK,              SpeechRecogniser.WHATS_MY_GAP_BEHIND_ON_TRACK},
            {ID.WHATS_MY_GAP_IN_FRONT,                     SpeechRecogniser.WHATS_MY_GAP_IN_FRONT},
            {ID.WHATS_MY_GAP_IN_FRONT_ON_TRACK,            SpeechRecogniser.WHATS_MY_GAP_IN_FRONT_ON_TRACK},
            {ID.WHATS_MY_GAP_TO_LEADER,                    SpeechRecogniser.WHATS_MY_GAP_TO_LEADER},
            {ID.WHATS_MY_IRATING,                          SpeechRecogniser.WHATS_MY_IRATING},
            {ID.WHATS_MY_LAST_SECTOR_TIME,                 SpeechRecogniser.WHATS_MY_LAST_SECTOR_TIME},
            {ID.WHATS_MY_LICENSE_CLASS,                    SpeechRecogniser.WHATS_MY_LICENSE_CLASS},
            {ID.WHATS_MY_POSITION,                         SpeechRecogniser.WHATS_MY_POSITION},
            {ID.WHATS_MY_RANK,                             SpeechRecogniser.WHATS_MY_RANK},
            {ID.WHATS_MY_RATING,                           SpeechRecogniser.WHATS_MY_RATING},
            {ID.WHATS_MY_REPUTATION,                       SpeechRecogniser.WHATS_MY_REPUTATION},
            {ID.WHATS_PITLANE_SPEED_LIMIT,                 SpeechRecogniser.WHATS_PITLANE_SPEED_LIMIT},
            {ID.WHATS_THE_AIR_TEMP,                        SpeechRecogniser.WHATS_THE_AIR_TEMP},
            {ID.WHATS_THE_FASTEST_LAP_TIME,                SpeechRecogniser.WHATS_THE_FASTEST_LAP_TIME},
            {ID.WHATS_THE_INCIDENT_LIMIT,                  SpeechRecogniser.WHATS_THE_INCIDENT_LIMIT},
            {ID.WHATS_THE_LEADER_LAP,                      SpeechRecogniser.WHATS_THE_LEADER_LAP},
            {ID.WHATS_THE_SOF,                             SpeechRecogniser.WHATS_THE_SOF},
            {ID.WHATS_THE_TIME,                            SpeechRecogniser.WHATS_THE_TIME},
            {ID.WHATS_THE_TRACK_TEMP,                      SpeechRecogniser.WHATS_THE_TRACK_TEMP},
            {ID.WHATS_MY_BRAKE_BIAS,                       SpeechRecogniser.WHATS_MY_BRAKE_BIAS},
            {ID.WHEN_DID_IN_FRONT_ON_TRACK_PIT,            SpeechRecogniser.WHEN_DID_IN_FRONT_ON_TRACK_PIT},
            {ID.WHEN_DID_BEHIND_ON_TRACK_PIT,              SpeechRecogniser.WHEN_DID_BEHIND_ON_TRACK_PIT},
            {ID.WHERE_AM_I_FASTER,                         SpeechRecogniser.WHERE_AM_I_FASTER},
            {ID.WHERE_AM_I_SLOWER,                         SpeechRecogniser.WHERE_AM_I_SLOWER},
            {ID.WHERE_SHOULD_I_LINE_UP,                    SpeechRecogniser.WHERE_SHOULD_I_LINE_UP},
            {ID.WHOS_BEHIND_IN_THE_RACE,                   SpeechRecogniser.WHOS_BEHIND_IN_THE_RACE},
            {ID.WHOS_BEHIND_ON_TRACK,                      SpeechRecogniser.WHOS_BEHIND_ON_TRACK},
            {ID.WHOS_IN_FRONT_IN_THE_RACE,                 SpeechRecogniser.WHOS_IN_FRONT_IN_THE_RACE},
            {ID.WHOS_IN_FRONT_ON_TRACK,                    SpeechRecogniser.WHOS_IN_FRONT_ON_TRACK},
            {ID.WHOS_LEADING,                              SpeechRecogniser.WHOS_LEADING},
            {ID.WHOS_TWO_IN_FRONT_IN_THE_RACE,             SpeechRecogniser.WHOS_TWO_IN_FRONT_IN_THE_RACE},
            {ID.WHAT_TYRE_IS__,                            new string[] {SpeechRecogniser.WHAT_TYRE_IS} },
            {ID.WHAT_TYRES_IS__,                           new string[] {SpeechRecogniser.WHAT_TYRES_IS} },
            {ID.WHATS__BEST_LAP,                           new string[] {SpeechRecogniser.BEST_LAP} },
            {ID.WHATS__BEST_LAP_TIME,                      new string[] {SpeechRecogniser.BEST_LAP_TIME} },
            {ID.WHATS__IRATING,                            new string[] {SpeechRecogniser.IRATING} },
            {ID.WHATS__LAST_LAP,                           new string[] {SpeechRecogniser.LAST_LAP} },
            {ID.WHATS__LAST_LAP_TIME,                      new string[] {SpeechRecogniser.LAST_LAP_TIME} },
            {ID.WHATS__LICENSE_CLASS,                      new string[] {SpeechRecogniser.LICENSE_CLASS} },
            {ID.WHATS__RATING,                             new string[] {SpeechRecogniser.RATING} },
            {ID.WHATS__REPUTATION,                         new string[] {SpeechRecogniser.REPUTATION} },
            {ID.WHATS__RANK,                               new string[] {SpeechRecogniser.RANK} },
            {ID.WHERE_IS__,                                new string[] {SpeechRecogniser.WHERE_IS} },
            {ID.WHERES__,                                  new string[] {SpeechRecogniser.WHERES} },
            {ID.WHOS_IN__,                                 new string[] {SpeechRecogniser.WHOS_IN} },
        };

        /// <summary>
        /// Dictionary of SpeechCommand identifiers and their corresponding
        /// controller strings
        /// </summary>
        internal static readonly Dictionary<ID, string> controllerCommands = new Dictionary<ID, string>
        {
            {ID.ADD_TRACK_LANDMARK,                  ControllerConfiguration.ADD_TRACK_LANDMARK},
            {ID.CHANNEL_OPEN_FUNCTION,               ControllerConfiguration.CHANNEL_OPEN_FUNCTION},
            {ID.GET_CAR_STATUS,                      ControllerConfiguration.GET_CAR_STATUS},
            {ID.GET_DAMAGE_REPORT,                   ControllerConfiguration.GET_DAMAGE_REPORT},
            {ID.GET_FUEL_STATUS,                     ControllerConfiguration.GET_FUEL_STATUS},
            {ID.GET_SESSION_STATUS,                  ControllerConfiguration.GET_SESSION_STATUS},
            {ID.GET_STATUS,                          ControllerConfiguration.GET_STATUS},
            {ID.PIT_PREDICTION,                      ControllerConfiguration.PIT_PREDICTION},
            {ID.PRINT_TRACK_DATA,                    ControllerConfiguration.PRINT_TRACK_DATA},
            {ID.READ_CORNER_NAMES_FOR_LAP,           ControllerConfiguration.READ_CORNER_NAMES_FOR_LAP},
            {ID.REPEAT_LAST_MESSAGE_BUTTON,          ControllerConfiguration.REPEAT_LAST_MESSAGE_BUTTON},
            {ID.RESET_VR_VIEW,                       ControllerConfiguration.RESET_VR_VIEW},
            {ID.TOGGLE_BLOCK_MESSAGES_IN_HARD_PARTS, ControllerConfiguration.TOGGLE_BLOCK_MESSAGES_IN_HARD_PARTS},
            {ID.TOGGLE_ENABLE_CUT_TRACK_WARNINGS,    ControllerConfiguration.TOGGLE_ENABLE_CUT_TRACK_WARNINGS},
            {ID.TOGGLE_MANUAL_FORMATION_LAP,         ControllerConfiguration.TOGGLE_MANUAL_FORMATION_LAP},
            {ID.TOGGLE_MUTE,                         ControllerConfiguration.TOGGLE_MUTE},
            {ID.TOGGLE_PACE_NOTES_PLAYBACK,          ControllerConfiguration.TOGGLE_PACE_NOTES_PLAYBACK},
            {ID.TOGGLE_PACE_NOTES_RECORDING,         ControllerConfiguration.TOGGLE_PACE_NOTES_RECORDING},
            {ID.TOGGLE_RALLY_RECCE_MODE,             ControllerConfiguration.TOGGLE_RALLY_RECCE_MODE},
            {ID.TOGGLE_RACE_UPDATES_FUNCTION,        ControllerConfiguration.TOGGLE_RACE_UPDATES_FUNCTION},
            {ID.TOGGLE_READ_OPPONENT_DELTAS,         ControllerConfiguration.TOGGLE_READ_OPPONENT_DELTAS},
            {ID.TOGGLE_SPOTTER_FUNCTION,             ControllerConfiguration.TOGGLE_SPOTTER_FUNCTION},
            {ID.TOGGLE_TRACK_LANDMARKS_RECORDING,    ControllerConfiguration.TOGGLE_TRACK_LANDMARKS_RECORDING},
            {ID.TOGGLE_YELLOW_FLAG_MESSAGES,         ControllerConfiguration.TOGGLE_YELLOW_FLAG_MESSAGES},
            {ID.VOLUME_DOWN,                         ControllerConfiguration.VOLUME_DOWN},
            {ID.VOLUME_UP,                           ControllerConfiguration.VOLUME_UP},
        };
        #endregion IDs and tables

        internal static bool tableCheck()
        {
            foreach (var id in Enum.GetValues(typeof(ID)))
            {
                if (!speechCommands.ContainsKey((ID)id) &&
                    (ID)id != ID.NO_COMMAND)
                {
                    if (!controllerCommands.ContainsKey((ID)id))
                    {
                        Console.WriteLine("Missing " + id);
                        return false;
                    }
                }
            }
            return true;
        }
        /// <summary>
        /// Given a list of SpeechCommand identifiers return each with its corresponding
        /// speech strings
        /// </summary>
        /// <param name="commandList">SpeechCommand identifiers</param>
        /// <returns>SpeechCommand identifier,its corresponding speech strings</returns>
        public static IEnumerable<(ID, string[])> GenerateTuples(List<ID> commandList)
        {
            foreach (var command in commandList)
            {
                if (speechCommands.TryGetValue(command, out string[] speechCommand))
                {
                    yield return (command, speechCommand);
                }
            }
        }

        /// <summary>
        /// Convert recognised speech into a SpeechCommand enum
        /// </summary>
        /// <param name="commands">Possible commands</param>
        /// <param name="recognisedSpeech">The recognised speech</param>
        /// <returns>SpeechCommand ID, NO_COMMAND if no match</returns>
        public static ID SpeechToCommand(List<ID> commands, string recognisedSpeech, Boolean logMatch = false)
        {
            ID cmd = ID.NO_COMMAND;
            foreach (var command in GenerateTuples(commands))
            {
                if (SpeechRecogniser.ResultContains(recognisedSpeech, command.Item2, logMatch))
                {
                    cmd = command.Item1;
                    break;
                }
            }
            return cmd;
        }

        /// <summary>
        /// Convert recognised speech into a SpeechCommand enum
        /// </summary>
        /// <param name="commands">Possible commands</param>
        /// <param name="recognisedSpeech">The recognised speech</param>
        /// <returns>SpeechCommand ID, NO_COMMAND if no match</returns>
        public static ID SpeechEndsWithToCommand(List<ID> commands, string recognisedSpeech, Boolean logMatch = false)
        {
            ID cmd = ID.NO_COMMAND;
            foreach (var command in GenerateTuples(commands))
            {
                if (recognisedSpeech.EndsWith(command.Item2[0]))
                {
                    cmd = command.Item1;
                    break;
                }
            }
            return cmd;
        }

        /// <summary>
        /// Convert recognised speech into a SpeechCommand enum
        /// </summary>
        /// <param name="commands">Possible commands</param>
        /// <param name="recognisedSpeech">The recognised speech</param>
        /// <returns>SpeechCommand ID, NO_COMMAND if no match</returns>
        public static ID SpeechStartsWithToCommand(List<ID> commands, string recognisedSpeech, Boolean logMatch = false)
        {
            ID cmd = ID.NO_COMMAND;
            foreach (var command in GenerateTuples(commands))
            {
                if (recognisedSpeech.StartsWith(command.Item2[0]))
                {
                    cmd = command.Item1;
                    break;
                }
            }
            return cmd;
        }

        /// <summary>
        /// Given a list of SpeechCommand identifiers return each with its corresponding
        /// controller label
        /// </summary>
        /// <param name="commandList">SpeechCommand identifiers</param>
        /// <returns>SpeechCommand identifier,its corresponding controller label</returns>
        public static IEnumerable<(ID, string)> GenerateTuples2(List<ID> commandList)
        {
            foreach (var command in commandList)
            {
                if (controllerCommands.TryGetValue(command, out string controllerCommand))
                {
                    yield return (command, controllerCommand);
                }
            }
        }

        /// <summary>
        /// Convert controller button label into a SpeechCommand enum
        /// </summary>
        /// <param name="commands">Possible commands</param>
        /// <param name="controllerLabel">The recognised speech</param>
        /// <returns>SpeechCommand ID, NO_COMMAND if no match</returns>
        public static ID ControllerToCommand(List<ID> commands, string controllerLabel)
        {
            ID cmd = ID.NO_COMMAND;
            if (ControllerConfiguration.builtInActionMappings.ContainsValue(controllerLabel))
            {
                foreach (var command in GenerateTuples2(commands))
                {
                    if (command.Item2.Contains(controllerLabel))
                    {
                        cmd = command.Item1;
                        break;
                    }
                }
            }
            return cmd;
        }
    }
}
