name: Build CrewChiefV4

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore CrewChiefV4.sln

      - name: Build CrewChiefV4
        run: msbuild CrewChiefV4\CrewChiefV4.csproj /p:Configuration=Release /p:Platform=AnyCPU /verbosity:minimal

      - name: Run test_runner Unit Tests
        run: dotnet test test_runner\test_runner.csproj -c Release

      - name: Archive Production Executable & Binaries
        uses: actions/upload-artifact@v4
        with:
          name: CrewChiefV4-Release-Build
          path: CrewChiefV4\bin\Release\
          if-no-files-found: error
